import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, Plus, Users, Calendar, Award, TrendingUp, Bell, CheckCircle2, Star, Clock } from "lucide-react";
import { 
    AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer,
    LineChart, Line
} from 'recharts';

import Button from "@components/common/Button";
import Input from "@components/common/Input";

import KpiCard from "@school-admin/components/KpiCard";
import SectionCard from "@school-admin/components/SectionCard";
import ResultsTable from "@school-admin/components/ResultsTable";
import ResultDetailsModal from "@school-admin/components/ResultDetailsModal";

// Interactive Modals
import UserFormModal from "@admin/components/UserFormModal";
import TeacherFormModal from "@school-admin/components/TeacherFormModal";

import { useResults, useStudents, useTeachers } from "@school-admin/hooks/useSchoolData";
import { getInitials } from "@utils/formatters";

// Mock Data for Performance Chart
const performanceData = [
    { month: 'Jan', avgScore: 65, tests: 120 },
    { month: 'Feb', avgScore: 68, tests: 140 },
    { month: 'Mar', avgScore: 72, tests: 190 },
    { month: 'Apr', avgScore: 75, tests: 210 },
    { month: 'May', avgScore: 82, tests: 250 },
    { month: 'Jun', avgScore: 85, tests: 300 },
];

// Mock Data for Activity Feed
const recentActivities = [
    { id: 1, type: "achievement", message: "Rahul reached Level 5!", time: "10 mins ago", icon: Star, color: "text-amber-500", bg: "bg-amber-500/10" },
    { id: 2, type: "test", message: "Class 10 completed English Test", time: "2 hours ago", icon: CheckCircle2, color: "text-emerald-500", bg: "bg-emerald-500/10" },
    { id: 3, type: "user", message: "New Teacher Mr. Sharma added", time: "4 hours ago", icon: Users, color: "text-[var(--color-primary)]", bg: "bg-[var(--color-primary)]/10" },
    { id: 4, type: "test", message: "Math Quiz generated by AI", time: "1 day ago", icon: Award, color: "text-purple-500", bg: "bg-purple-500/10" },
];

export function Dashboard() {
    const { results, totalResults, searchTerm, setSearchTerm } = useResults();
    const { students, addStudent } = useStudents();
    const { teachers, addTeacher } = useTeachers();
    
    // UI States
    const [selectedResult, setSelectedResult] = useState(null);
    const [isExporting, setIsExporting] = useState(false);
    
    // Modal States
    const [studentModalOpen, setStudentModalOpen] = useState(false);
    const [teacherModalOpen, setTeacherModalOpen] = useState(false);

    const recentResults = results.slice(0, 5);
    const avgScore = results.length > 0 ? Math.round(results.reduce((acc, r) => acc + r.percentage, 0) / results.length) : 0;
    
    // Get top 5 students by XP
    const topStudents = [...students].sort((a, b) => (b.progress?.xp || 0) - (a.progress?.xp || 0)).slice(0, 5);

    const topRowKpis = [
        { id: "total-students", label: "Total Students", value: students.length, change: 4.2, trend: "up", icon: "users", accent: "#6c63ff", sparkline: [110, 112, 115, 118, 119, 121, 122, 123, 123.5, students.length] },
        { id: "active-students", label: "Active Students", value: students.filter(s => s.status === 'active').length, change: 2.1, trend: "up", icon: "users", accent: "#22c55e", sparkline: [85, 87, 88, 90, 91, 93, 94, 95, 96, 98] },
    ];

    const secondRowKpis = [
        { id: "total-tests", label: "Total Tests", value: totalResults, change: 12.5, trend: "up", icon: "clipboard", accent: "#6c63ff", sparkline: [15, 17, 18, 19, 20, 21, 22, 23, 23.5, totalResults] },
        { id: "recent-results", label: "Recent Results", value: 12, change: 8.0, trend: "up", icon: "chart", accent: "#ff6584", sparkline: [20, 22, 23, 24, 25, 26, 27, 28, 29, 32] },
        { id: "avg-score", label: "School Avg Score", value: `${avgScore}%`, change: 5.2, trend: "up", icon: "award", accent: "#eab308", sparkline: [75, 76, 78, 80, 81, 80, 83, 85, 87, avgScore] },
    ];

    const handleExport = () => {
        setIsExporting(true);
        setTimeout(() => setIsExporting(false), 2000);
    };

    const handleAddStudent = (data) => {
        addStudent(data);
        setStudentModalOpen(false);
    };

    const handleAddTeacher = (data) => {
        addTeacher(data);
        setTeacherModalOpen(false);
    };

    return (
        <div className="space-y-5 sm:space-y-6">
            
            {/* Header section with gradient and quick actions */}
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
                className="relative overflow-hidden rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-5 shadow-[var(--shadow-sm)] sm:p-8"
            >
                <div className="pointer-events-none absolute -right-16 -top-16 h-56 w-56 rounded-full opacity-20 blur-3xl"
                    style={{ background: "linear-gradient(135deg,#6c63ff,#ff6584)" }}
                />
                <div className="relative flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
                    <div className="min-w-0">
                        <span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 py-1 text-[11px] font-semibold uppercase tracking-wider text-[var(--text-secondary)] shadow-sm">
                            <span className="relative flex h-2 w-2">
                                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                                <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                            </span>
                            Live Dashboard
                        </span>
                        <h1 className="mt-3 text-2xl font-bold tracking-tight text-[var(--text-primary)] sm:text-3xl">
                            Command Center
                        </h1>
                        <p className="mt-1.5 max-w-xl text-sm leading-6 text-[var(--text-secondary)]">
                            Monitor students, track real-time performance, and manage school operations.
                        </p>

                        {/* School Details */}
                        <div className="mt-4 flex flex-wrap items-center gap-3 text-xs font-medium text-[var(--text-secondary)]">
                            <div className="flex items-center gap-1.5 rounded-lg bg-[var(--bg-elevated)] px-2.5 py-1.5 border border-[var(--border-subtle)] shadow-sm transition hover:border-[var(--color-primary)]">
                                <span className="text-[var(--text-muted)]">School:</span>
                                <span className="text-[var(--text-primary)] font-bold">Greenwood High</span>
                            </div>
                            <div className="flex items-center gap-1.5 rounded-lg bg-[var(--bg-elevated)] px-2.5 py-1.5 border border-[var(--border-subtle)] shadow-sm transition hover:border-[var(--color-primary)]">
                                <span className="text-[var(--text-muted)]">Code:</span>
                                <span className="text-[var(--text-primary)] font-bold">GH-4592</span>
                            </div>
                            <div className="flex items-center gap-1.5 rounded-lg bg-[var(--bg-elevated)] px-2.5 py-1.5 border border-[var(--border-subtle)] shadow-sm transition hover:border-[var(--color-primary)]">
                                <span className="text-[var(--text-muted)]">Location:</span>
                                <span className="text-[var(--text-primary)] font-bold">New York, NY</span>
                            </div>
                        </div>
                    </div>
                    
                    {/* Quick Actions Panel */}
                    <div className="flex shrink-0 flex-wrap gap-3 rounded-xl bg-[var(--bg-elevated)] p-2 border border-[var(--border-subtle)]">
                        <Button className="!h-10 !px-4 shadow-md hover:shadow-lg transition-transform hover:-translate-y-0.5" onClick={() => setStudentModalOpen(true)}>
                            <Plus className="mr-1.5 h-4 w-4" />
                            Add Student
                        </Button>
                        <Button variant="secondary" className="!h-10 !px-4 transition-transform hover:-translate-y-0.5" onClick={() => setTeacherModalOpen(true)}>
                            <Users className="mr-1.5 h-4 w-4" />
                            Add Teacher
                        </Button>
                        <Button 
                            variant="secondary" 
                            className={`!h-10 !px-4 transition-all ${isExporting ? 'bg-emerald-500/10 text-emerald-500 border-emerald-500/50' : ''}`}
                            onClick={handleExport}
                            disabled={isExporting}
                        >
                            {isExporting ? <CheckCircle2 className="mr-1.5 h-4 w-4" /> : <Download className="mr-1.5 h-4 w-4" />}
                            {isExporting ? "Exported!" : "Export Data"}
                        </Button>
                    </div>
                </div>
            </motion.div>

            {/* KPI Grids */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                {topRowKpis.map((kpi, i) => (
                    <KpiCard key={kpi.id} kpi={kpi} index={i} />
                ))}
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
                {secondRowKpis.map((kpi, i) => (
                    <KpiCard key={kpi.id} kpi={kpi} index={i} />
                ))}
            </div>

            {/* Performance Overview (Interactive Chart) */}
            <SectionCard delay={0.05} bodyClassName="p-5 sm:p-6">
                <div className="mb-6 flex items-center justify-between">
                    <div>
                        <h2 className="text-lg font-bold text-[var(--text-primary)]">Performance Overview</h2>
                        <p className="text-sm text-[var(--text-secondary)]">Average scores vs Total tests over time</p>
                    </div>
                    <div className="flex items-center gap-4 text-xs font-semibold">
                        <div className="flex items-center gap-2">
                            <span className="h-3 w-3 rounded-full bg-[var(--color-primary)]"></span>
                            <span className="text-[var(--text-secondary)]">Avg Score (%)</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="h-3 w-3 rounded-full bg-[#ff6584]"></span>
                            <span className="text-[var(--text-secondary)]">Total Tests</span>
                        </div>
                    </div>
                </div>
                <div className="h-[280px] w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <AreaChart data={performanceData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                            <defs>
                                <linearGradient id="colorScore" x1="0" y1="0" x2="0" y2="1">
                                    <stop offset="5%" stopColor="var(--color-primary)" stopOpacity={0.3}/>
                                    <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0}/>
                                </linearGradient>
                                <linearGradient id="colorTests" x1="0" y1="0" x2="0" y2="1">
                                    <stop offset="5%" stopColor="#ff6584" stopOpacity={0.3}/>
                                    <stop offset="95%" stopColor="#ff6584" stopOpacity={0}/>
                                </linearGradient>
                            </defs>
                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border-default)" />
                            <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 12 }} dy={10} />
                            <YAxis yAxisId="left" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 12 }} domain={[0, 100]} />
                            <YAxis yAxisId="right" orientation="right" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 12 }} />
                            <RechartsTooltip 
                                contentStyle={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-default)', borderRadius: '12px', boxShadow: 'var(--shadow-md)' }}
                                itemStyle={{ color: 'var(--text-primary)', fontWeight: 'bold' }}
                            />
                            <Area yAxisId="left" type="monotone" dataKey="avgScore" name="Avg Score" stroke="var(--color-primary)" strokeWidth={3} fillOpacity={1} fill="url(#colorScore)" activeDot={{ r: 6, strokeWidth: 0, fill: "var(--color-primary)" }} />
                            <Area yAxisId="right" type="monotone" dataKey="tests" name="Total Tests" stroke="#ff6584" strokeWidth={3} fillOpacity={1} fill="url(#colorTests)" activeDot={{ r: 6, strokeWidth: 0, fill: "#ff6584" }} />
                        </AreaChart>
                    </ResponsiveContainer>
                </div>
            </SectionCard>

            {/* Bottom Grid: Recent Results, Leaderboard, & Activity */}
            <div className="grid grid-cols-1 gap-5 lg:grid-cols-4">
                
                {/* Recent Results Table */}
                <SectionCard
                    title="Recent Results"
                    subtitle="Live test submissions"
                    className="lg:col-span-2"
                    delay={0.1}
                    bodyClassName="p-0"
                    action={
                        <div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center">
                            <Input
                                placeholder="Search results…"
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                            />
                        </div>
                    }
                >
                    <ResultsTable results={recentResults} onRowClick={setSelectedResult} />
                </SectionCard>

                {/* Gamified Leaderboard */}
                <SectionCard
                    title="Top Performers"
                    subtitle="Highest XP this month"
                    className="lg:col-span-1"
                    delay={0.15}
                    bodyClassName="p-0"
                    action={
                        <Button variant="secondary" className="!h-8 !px-3 !text-xs hidden sm:flex">
                            View All
                        </Button>
                    }
                >
                    <div className="flex flex-col">
                        {topStudents.map((student, index) => (
                            <div key={student.id} className="group flex items-center justify-between border-b border-[var(--border-subtle)] p-4 last:border-0 hover:bg-[var(--bg-hover)] transition-all cursor-pointer">
                                <div className="flex items-center gap-3">
                                    <div className="relative">
                                        <span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-sm font-bold text-white transition-transform group-hover:scale-110 ${
                                            index === 0 ? 'bg-amber-500 shadow-amber-500/30' : 
                                            index === 1 ? 'bg-slate-400 shadow-slate-400/30' : 
                                            index === 2 ? 'bg-amber-700 shadow-amber-700/30' : 
                                            'bg-gradient-to-br from-indigo-500 to-purple-500'
                                        } shadow-md`}>
                                            {getInitials(student.name)}
                                        </span>
                                        {index < 3 && (
                                            <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-[var(--bg-surface)] text-[10px] animate-bounce">
                                                {index === 0 ? '👑' : index + 1}
                                            </span>
                                        )}
                                    </div>
                                    <div className="min-w-0">
                                        <p className="truncate text-sm font-bold text-[var(--text-primary)] group-hover:text-[var(--color-primary)] transition-colors">{student.name}</p>
                                        <p className="truncate text-xs font-medium text-[var(--text-secondary)]">Level {student.progress?.level || 1}</p>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <p className="text-sm font-black text-[var(--text-primary)]">{student.progress?.xp?.toLocaleString() || 0}</p>
                                    <p className="text-[10px] font-bold uppercase tracking-wider text-[var(--color-primary)]">XP</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </SectionCard>

                {/* Live Activity Feed */}
                <SectionCard
                    title="Live Activity"
                    subtitle="Real-time school events"
                    className="lg:col-span-1"
                    delay={0.2}
                    bodyClassName="p-4 sm:p-5"
                    action={<Bell className="h-4 w-4 text-[var(--color-primary)] animate-pulse" />}
                >
                    <div className="relative border-l border-[var(--border-default)] ml-3 space-y-6">
                        {recentActivities.map((activity) => {
                            const Icon = activity.icon;
                            return (
                                <div key={activity.id} className="relative pl-6">
                                    <span className={`absolute -left-3 top-0.5 flex h-6 w-6 items-center justify-center rounded-full ${activity.bg} ${activity.color} ring-4 ring-[var(--bg-surface)]`}>
                                        <Icon className="h-3 w-3" />
                                    </span>
                                    <div className="flex flex-col gap-0.5">
                                        <p className="text-sm font-semibold text-[var(--text-primary)] leading-tight">{activity.message}</p>
                                        <p className="flex items-center gap-1 text-[11px] font-medium text-[var(--text-muted)]">
                                            <Clock className="h-3 w-3" />
                                            {activity.time}
                                        </p>
                                    </div>
                                </div>
                            )
                        })}
                    </div>
                </SectionCard>

            </div>

            {/* Test Breakdown Modal */}
            <ResultDetailsModal
                isOpen={Boolean(selectedResult)}
                result={selectedResult}
                onClose={() => setSelectedResult(null)}
            />

            {/* Interactive Modals */}
            <UserFormModal 
                isOpen={studentModalOpen}
                mode="add"
                teachers={teachers}
                isStudentForm={true}
                onClose={() => setStudentModalOpen(false)}
                onSubmit={handleAddStudent}
            />

            <TeacherFormModal 
                isOpen={teacherModalOpen}
                mode="add"
                onClose={() => setTeacherModalOpen(false)}
                onSubmit={handleAddTeacher}
            />

        </div>
    );
}

export default Dashboard;
